name: ecgtools-dev
channels:
  - accessnri
  - conda-forge
  - nodefaults
dependencies:
  - cf_xarray
  - codecov
  - fsspec
  - gcsfs
  - accessnri::intake-esm-access
  - joblib
  - nbsphinx
  - netcdf4
  - numpydoc
  - pip
  - pre-commit
  - pydantic>=2.0
  - pytest
  - pytest-cov
  - pytest-sugar
  - pytest-xdist
  - pytest-reportlog
  - pyyaml
  - s3fs
  - typer
  - xarray
  - pip:
      - git+https://github.com/xarray-contrib/cf-xarray
      - git+https://github.com/access-nri/intake-esm
