name: ecgtools-dev
channels:
  - accessnri
  - conda-forge
  - nodefaults
dependencies:
  - cf_xarray
  - fsspec
  - gcsfs
  - accessnri::intake-esm-access
  - joblib
  - netcdf4
  - pip
  - pre-commit
  - pydantic>=2.0
  - pytest
  - pytest-cov
  - pytest-sugar
  - pytest-xdist
  - pyyaml
  - s3fs
  - xarray