name: ecgtools-doc
channels:
  - accessnri
  - conda-forge
  - nodefaults
dependencies:
  - cf_xarray
  - fsspec
  - furo
  - gcsfs
  - joblib
  - jupyterlab
  - myst-nb
  - netcdf4
  - pip
  - pydantic>=2.0
  - s3fs
  - sphinx-copybutton
  - sphinx-inline-tabs
  - xarray
  - pip:
      - sphinxext-opengraph
      - -r ../requirements.txt
      - git+https://github.com/access-nri/intake-esm
      - -e ..
