name: CI
on:
  push:
    branches:
      - main
  pull_request:
  schedule:
    - cron: "0 0 * * *" # Daily “At 00:00”
  workflow_dispatch: # allows you to trigger manually

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5.0.0
      - uses: actions/setup-python@v6
      - uses: pre-commit/action@v3.0.1

  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        environment: [test-py310, test-py311, test-py312, test-py313]
    steps:
    - uses: actions/checkout@v5.0.0
    - uses: prefix-dev/setup-pixi@v0.8.3
      with:
        environments: ${{ matrix.environment }}
        frozen: true # This seems hacky?


    - name: Run tests and generate coverage report
      run: |
        pixi clean && pixi run -e ${{ matrix.environment }} test-cov

    - name: Upload code coverage
      uses: codecov/codecov-action@v5
      with:
        token: ${{ secrets.codecov_token }}
        files: ./coverage.xml